version: "3"

services:

      kafka-spark:
        build: .
        networks:
          - mybridge
        links:
          - kafka
        ports:
          - "8080:8080"
          - "4040:4040"
        hostname: kafka-spark
        image: kafka-spark
        container_name: kafka-spark

      zookeeper:
        image: wurstmeister/zookeeper
        networks:
          - mybridge
        ports:
          - "2181:2181"
        container_name: zookeeper
        hostname: zookeeper

      kafka:
        image: wurstmeister/kafka
        networks:
          - mybridge
        links:
          - zookeeper
        ports:
          - "9092:9092"
        environment:
          HOST_IP: kafka
          KAFKA_ADVERTISED_HOST_NAME: kafka
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_BROKER_ID: 1
          ZK: zookeeper
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        hostname: kafka
        container_name: kafka



networks:
  mybridge:





